# Generated by Django 3.1.4 on 2021-05-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('usertel', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('AppName', models.CharField(max_length=128)),
                ('appid', models.CharField(max_length=128)),
                ('appsecret', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('usertel', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=128)),
            ],
        ),
    ]
